import { IRelatedArtists, NewRelatedArtists } from './related-artists.model';

export const sampleWithRequiredData: IRelatedArtists = {
  id: 86494,
  mainArtistSptfyID: 'Croatia',
  relatedArtistSpotifyID1: 'Pizza Tuna Islands',
  relatedArtistSpotifyID2: 'Markets',
  relatedArtistSpotifyID3: 'Rubber optimizing microchip',
  relatedArtistSpotifyID4: 'Ruble',
  relatedArtistSpotifyID5: 'reboot Sports benchmark',
  relatedArtistSpotifyID6: 'COM optimal systems',
  relatedArtistSpotifyID7: 'Plastic International',
  relatedArtistSpotifyID8: 'fuchsia',
  relatedArtistSpotifyID9: 'navigating system array',
  relatedArtistSpotifyID10: 'Granite',
  relatedArtistSpotifyID11: 'lime',
  relatedArtistSpotifyID12: 'Won',
  relatedArtistSpotifyID13: 'Chips matrix',
  relatedArtistSpotifyID14: 'India',
  relatedArtistSpotifyID15: 'Iowa',
  relatedArtistSpotifyID16: 'Market',
  relatedArtistSpotifyID17: 'sticky auxiliary Towels',
  relatedArtistSpotifyID18: 'Automotive',
  relatedArtistSpotifyID19: 'hack Beauty',
  relatedArtistSpotifyID20: 'Rustic protocol payment',
};

export const sampleWithPartialData: IRelatedArtists = {
  id: 96950,
  mainArtistSptfyID: 'analyzing',
  relatedArtistSpotifyID1: 'Maryland',
  relatedArtistSpotifyID2: 'Skyway Massachusetts',
  relatedArtistSpotifyID3: 'Frozen Assurance',
  relatedArtistSpotifyID4: 'Sleek ability sky',
  relatedArtistSpotifyID5: 'encryption',
  relatedArtistSpotifyID6: 'Open-architected',
  relatedArtistSpotifyID7: '9(E.U.A.-9)',
  relatedArtistSpotifyID8: 'task-force York Soap',
  relatedArtistSpotifyID9: 'Representative red',
  relatedArtistSpotifyID10: 'input enhance',
  relatedArtistSpotifyID11: 'hacking Louisiana',
  relatedArtistSpotifyID12: 'distributed card',
  relatedArtistSpotifyID13: 'cohesive withdrawal',
  relatedArtistSpotifyID14: 'California',
  relatedArtistSpotifyID15: 'tangible Internal override',
  relatedArtistSpotifyID16: 'Technician',
  relatedArtistSpotifyID17: 'sensor optical Manager',
  relatedArtistSpotifyID18: 'synthesizing Australia National',
  relatedArtistSpotifyID19: 'Rubber redefine',
  relatedArtistSpotifyID20: 'Cambridgeshire maximized',
};

export const sampleWithFullData: IRelatedArtists = {
  id: 3357,
  mainArtistSptfyID: 'frictionless Bacon',
  relatedArtistSpotifyID1: 'Rustic Hong',
  relatedArtistSpotifyID2: 'interactive web-enabled',
  relatedArtistSpotifyID3: 'Plastic',
  relatedArtistSpotifyID4: 'transmitter',
  relatedArtistSpotifyID5: 'invoice',
  relatedArtistSpotifyID6: 'Supervisor Swaziland',
  relatedArtistSpotifyID7: 'multi-state',
  relatedArtistSpotifyID8: 'International monitor deposit',
  relatedArtistSpotifyID9: 'Quality',
  relatedArtistSpotifyID10: 'Utah 1080p',
  relatedArtistSpotifyID11: 'bypass Avon',
  relatedArtistSpotifyID12: 'Administrator Automotive',
  relatedArtistSpotifyID13: 'Square Outdoors Delaware',
  relatedArtistSpotifyID14: 'invoice',
  relatedArtistSpotifyID15: 'Reactive',
  relatedArtistSpotifyID16: 'teal generate',
  relatedArtistSpotifyID17: 'Anguilla',
  relatedArtistSpotifyID18: 'Self-enabling compress Generic',
  relatedArtistSpotifyID19: 'architectures Crossroad',
  relatedArtistSpotifyID20: 'transmit Pula',
};

export const sampleWithNewData: NewRelatedArtists = {
  mainArtistSptfyID: 'bus',
  relatedArtistSpotifyID1: 'Fresh Triple-buffered Way',
  relatedArtistSpotifyID2: 'AGP',
  relatedArtistSpotifyID3: 'Cotton deposit Unbranded',
  relatedArtistSpotifyID4: 'composite',
  relatedArtistSpotifyID5: 'SMS',
  relatedArtistSpotifyID6: 'Senior Berkshire',
  relatedArtistSpotifyID7: 'Clothing',
  relatedArtistSpotifyID8: 'teal',
  relatedArtistSpotifyID9: 'Cotton Directives online',
  relatedArtistSpotifyID10: 'Mouse',
  relatedArtistSpotifyID11: 'Borders',
  relatedArtistSpotifyID12: 'system deposit',
  relatedArtistSpotifyID13: 'integrated Borders',
  relatedArtistSpotifyID14: 'Plastic',
  relatedArtistSpotifyID15: 'program',
  relatedArtistSpotifyID16: 'e-commerce',
  relatedArtistSpotifyID17: 'Intelligent',
  relatedArtistSpotifyID18: 'Practical invoice compressing',
  relatedArtistSpotifyID19: 'Svalbard Buckinghamshire Buckinghamshire',
  relatedArtistSpotifyID20: 'SSL',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
