# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    team.bham: INFO

management:
  metrics:
    export:
      prometheus:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/teamproject
    username: teamproject
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: tech.jhipster.domain.util.FixedPostgreSQL10Dialect
  # Replace by 'prod, faker' to add the faker context and have sample data loaded in production
  liquibase:
    contexts: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2fa.lowertones@gmail.com
    password: uetidoqwhkpunyxx
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  thymeleaf:
    cache: true

# ===================================================================
# To enable TLS in production, generate a certificate using:
# keytool -genkey -alias teamproject -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# See details in topic "Create a Java Keystore (.JKS) from Let's Encrypt Certificates" on https://maximilian-boehm.com/en-gb/blog
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#   port: 443
#   ssl:
#     key-store: classpath:config/tls/keystore.p12
#     key-store-password: password
#     key-store-type: PKCS12
#     key-alias: selfsigned
#     # The ciphers suite enforce the security by deactivating some old and deprecated SSL cipher, this list was tested against SSL Labs (https://www.ssllabs.com/ssltest/)
#     ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 ,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 ,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_RSA_WITH_CAMELLIA_256_CBC_SHA,TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA,TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
# ===================================================================
server:
  port: 8080
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 1000 # Number of objects in each cache entry
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        # As this is the PRODUCTION configuration, you MUST change the default key, and store it securely:
        # - In the JHipster Registry (which includes a Spring Cloud Config server)
        # - In a separate `application-prod.yml` file, in the same folder as your executable JAR file
        # - In the `JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET` environment variable
        base64-secret: ZmE3NjRlMDUyNGU2NmYwMGY3MTdhMWQ0NDY3OTVkYTlmY2NiZGIyMGZlNzMyNmI4MWIwOGJiZTljOTg2OGM1YjBkMjc5ZGFkZTE1ZDRlZjI0YmM0MWM2OGQ2YmYwNDg1MDQxM2VlZDZmMThjOGE0YjRlZGJkYzQ0MGEzMTI2NDc=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: https://team37.bham.team # Modify according to your server's URL
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

#application:
#  security:
#    spotifyAppSecretID: 8758afca4e884efc91eefc0d3891cfd7
spotify:
  client:
    id: f7a2bfcf05ea495ea670e320a947b96b
    secret: 9e318c3460114b82b1021d20f8d6e089

drive:
  login: '{"type": "service_account","project_id": "lowertones","private_key_id": "707cc19214ac2a43267302977064e5b1b7b58c2d","private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDTKjUwT32hZ2jg\nDgz+ulk786ZF4pKPE947zrJkvBYpnbkR+v39q41ti1k614qO7EIGfI4LNTzmqXuT\nqdpNjupAN2SG8JqsMKn/oOrfmYV0QvQl0Mc5d/YWFeKj9ZAdLYzqHMds9assJ1tt\nritzME5Pq7KN3rlTeY63qTQKMUAdUl0JwvAW04EY0pc6SG9pugnPYo/LEYv/0TPy\nePUlwK4N1QusQEn5OlgL39SKeuZHg6PqqTzdD58/UnzyRjXgPyj9cY6IfUo8/V1i\nO35fy92vRKDFMk/g1YL/i1POEaQaC/l9sLJfZYnwYwW7Aq5nXfAYwR8gBkY4vRjc\n7crX5IQfAgMBAAECggEAHpItwSDA/20JMebW2sn/wT41BEkZDr3Bnsb97LeOPdgn\nwwKjYuZDQ2i5MluiI67woB/IMLc0afB/g5FDmZbnMwTR+Pc8bVFeSzPwzQ5c08gd\nsJvZO+iyJ+BjP3l9s7u0evBPruaiMXJBOk/M2pBTxhUFdKSaEAu5Lb3BWvhmX9gZ\nNE88bdh8N4OR0RYk/eIXe5LJ3ZK/nf3H6U7uTlGy62XlZDyfMKN6aDvzIiMXVXC0\naNb/HBxNpwqtpUke1RfOPixFnhvpwrqFcq8VsfseCqLMocbEIaELyNQY7l5dl6F4\nz8hbVnauKH2hJARmfGdS/P4rYDa1qOnvS9Dy4yrtAQKBgQD8RzAHZPDKMlXfjsUo\nPgf+tZ1oSeAceof7ReT8BE7EjVLB6yWWZtAus0YsHt9Z/pccJH7EmRCtJan21iA9\nk6sn9Gqvs9E4t+BqwCJ6II0NdZbTsHrtuNNuE3n3UePoDZ7f3hZySRvdIM7dDoTR\nzKvo3MB5f1M6D12qE8fXal+KlwKBgQDWR74PMfgHMnkDF6fPDGv2cSD12VoXbuhc\nUHDMvUopeO6f0lFvb85zSHSoCk5zBBD1mdMNHo+8DAz790Vfhj9M2o0HIXlYyaNr\nJ18oezrtbQdmNkwpYGvrNlLuxBOCeGCRmmP8xe/BjhLR22XVrOLTvscBMUOCdV0N\nf1IFBD4ruQKBgQDhxWezRl/D5JY7cw74u8L17V0Ihwy9D9+APYX3EHfZqUxF5YaG\n+k4XbTNAqwRiCtj7Q6H7max1+H4KPIkv8ma7ZB7STY/RPaXmgzqXp2f0gqbPnmH1\nO3JkUaPWdYAMHZxwZtYZw1nfZMwcwzCUfaHfzSen1A4MqNG/MuKm4zjL0wKBgAvU\nVhe8qHatQKT9D1SM2QD36dvoreKRSt6dyjxjTs7PUE0ebUR7pagTne0Q9JfA57bH\nUTFuOH0nJShb1EabwK7beeGk5XATYaQuvkAb3XryA/COmtHF8u8/RoDL7k/LmXkw\nTsjLnJrQ3xUayZpsOvF5nL7iG1n+ZK60ErEYNN5xAoGBAOx6ZZtgOxiOABCC1Vtv\nZkpDJN/LP1x1LCdZnrej/imxfQpW+EMr4oII8jqrlVnfhqqp1kcjVOKcG5ik12F7\nfuivSOYgadzwig7Iby5odMi5qeS+vRPnmww4SnDiIS6hbY1OM0/FrAaSkN/Dt9Jx\nUqZMkQXLK6+c21u7KQgz1jRQ\n-----END PRIVATE KEY-----\n","client_email": "lowertones@lowertones.iam.gserviceaccount.com","client_id": "116882382266187662534","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://oauth2.googleapis.com/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/lowertones%40lowertones.iam.gserviceaccount.com","universe_domain": "googleapis.com"}'
